return {

	AssetTypes = {

		Back = "BackAccessory",
		Eyebrow = "EyebrowAccessory",
		Eyelash = "EyelashAccessory",
		Face = "FaceAccessory",
		Front = "FrontAccessory",
		Hair = "HairAccessory",
		Hat = "HatAccessory",
		Jacket = "JacketAccessory",
		LeftShoe = "LeftShoeAccessory",
		Neck = "NeckAccessory",
		Pants = "PantsAccessory",
		RightShoe = "RightShoeAccessory",
		Shirt = "ShirtAccessory",
		Shorts = "ShortsAccessory",
		Shoulder = "ShouldersAccessory",
		Sweater = "SweaterAccessory",
		TShirt = "TShirtAccessory",
	},
}
