return {

	AssetTypes = {

		TShirtAccessory = "TShirtAccessory",
		ShirtAccessory = "ShirtAccessory",
		PantsAccessory = "PantsAccessory",
		JacketAccessory = "JacketAccessory",
		SweaterAccessory = "SweaterAccessory",
		ShortsAccessory = "ShortsAccessory",
		LeftShoeAccessory = "LeftShoeAccessory",
		RightShoeAccessory = "RightShoeAccessory",
		EarAccessory = "EarAccessory",
		EyeAccessory = "EyeAccessory",
		Hat = "HatAccessory",
	},
}
