return {
	Badges = {
		["FirstPurchase"] = 0,
		["FiveTimesFullOutfitPurchase"] = 0,
		["FullOutfitPurchase"] = 0,
		["NiceToMeetYou"] = 0,
		["Welcome"] = 0,
	},

	Donates = {
		["DONATE_100"] = 0,
		["DONATE_1000"] = 0,
		["DONATE_10000"] = 0,
		["DONATE_100000"] = 0,
		["DONATE_25000"] = 0,
		["DONATE_500"] = 0,
		["DONATE_5000"] = 0,
		["DONATE_50000"] = 0,
	},

	Others = {
		["DEFAULT_MUSIC_ID"] = 0,
		["NotifyPurchaseWebhookURL"] = "https://discord.com/api/webhooks/1432551793564586025/4lPZZsyc0yyp0qzSJqpHBb8kbUY_49DEFAP4QJyG5NcKG1tMcS9spFf-16ta1hO7p9H7",
		["PLAYER_MODEL_RANGE"] = 20,
		["RUN_SPEED"] = 32,
		["GROUP_ID"] = 918388630,
	},

	Toggles = {
		["TeleportMenu"] = false,
	},
}
